!--------------------------------------------------------------------
! Copyright © 2017 United States Government as represented by the   |
! Administrator of the National Aeronautics and Space               |
! Administration. No copyright is claimed in the United States      |
! under Title 17, U.S. Code. All Other Rights Reserved.             |
!                                                                   |
! Licensed under the Apache License, Version 2.0.                   |
!--------------------------------------------------------------------

      ! Error codes
      integer, parameter :: SUCCESS = 0
      integer, parameter :: OUT_OF_RANGE = 1
      integer, parameter :: BAD_ALLOC = 2
      integer, parameter :: ILLEGAL_INPUT = 3

      ! private type for separating RC
      type :: KeywordEnforcer
      end type KeywordEnforcer

      

