!--------------------------------------------------------------------
! Copyright © 2017 United States Government as represented by the   |
! Administrator of the National Aeronautics and Space               |
! Administration. No copyright is claimed in the United States      |
! under Title 17, U.S. Code. All Other Rights Reserved.             |
!                                                                   |
! Licensed under the Apache License, Version 2.0.                   |
!--------------------------------------------------------------------

#undef __QUOTE
#undef __ASSIGN_DIM

#undef IMPURE_ELEMENTAL
#ifdef SUPPORT_FOR_INT64
#  undef SUPPORT_FOR_INT64
#endif
#undef __tmplbase_inc
