!--------------------------------------------------------------------
! Copyright © 2017 United States Government as represented by the   |
! Administrator of the National Aeronautics and Space               |
! Administration. No copyright is claimed in the United States      |
! under Title 17, U.S. Code. All Other Rights Reserved.             |
!                                                                   |
! Licensed under the Apache License, Version 2.0.                   |
!--------------------------------------------------------------------

#undef __QUOTE
#undef __ALLOC_SET

#undef _pointer
#undef _dim
#undef _string
#undef _logical

#undef _entry
#undef _bufentry
#undef _wrapentry
#undef _ptrentry
#undef _trgentry

#undef __GET
#undef __SET
#undef __EQ_ONE
#undef __EQ
#undef _wrapper
#undef EQUAL_DEFINED
#undef __tmplbase_inc
