!--------------------------------------------------------------------
! Copyright © 2017 United States Government as represented by the   |
! Administrator of the National Aeronautics and Space               |
! Administration. No copyright is claimed in the United States      |
! under Title 17, U.S. Code. All Other Rights Reserved.             |
!                                                                   |
! Licensed under the Apache License, Version 2.0.                   |
!--------------------------------------------------------------------

#undef _pointer
#undef _dim
#undef _string
#undef _logical
#undef __QUOTE
#undef _entry
#undef _bufentry
#undef _wrapentry
#undef _retentry
#undef __GET
#undef __SET
#undef __EQ
#undef _wrapper
#undef EQUAL_DEFINED
#undef _sfx
#undef _allocsfx
